# Generated by Django 4.0.1 on 2022-02-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='foods',
            name='kcal',
            field=models.IntegerField(blank=True),
        ),
    ]
