# Generated by Django 4.0.1 on 2022-04-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entry_type_alter_entry_date_alter_foods_kcal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
